--- 
title: "Analysing Flights with R"
author: "David Marsh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a training and reference manual for Eurocontrol staff, on how to use RStudio to analyse our traffic data."
---

# How to use this book {#howto}


## Before you start

You need to have RStudio and R installed on your machine. 

We assume that you are familiar with air traffic data, so won't spend time explaining the concepts.

This book is available as html here (TBD) and can be downloaded complete with data from here (TBD).

If you're working through the book as training, then it will help to install (TBD - training bundle)

If you want a more speedy introduction, then Enrico Spinielli has covered the [important steps here.](https://github.com/euctrl-pru/portal/wiki/Intro-to-everything).

There are also several useful 'cheat sheets' see (TBD)

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


## Ways to Use the Material

The book aims to support you using it in a number of different ways:

* Training. Work through chapters in order, or pick out specific chapters if you need a refresher on a topic. Read the explanations, grab the code and run it, and test your understanding by answering questions and doing exercises.

* Reference. Use the search to find some how-to material directly.

* Snippets. The book builds up snippets of usable code (TBD - how complete?) for you to cut-and-paste.

But it is never going to replace the huge amount of excellent information, especially in [stackoverflow](https://stackoverflow.com/). A key principle is that _"Google is your friend"_: even if I prefer [DuckDuckGo](https://www.duckduckgo.com) for many purposes, a google search is often more productive for R. Whether it's for how to do something, or how to respond to an error, usually someone has already suffered, and some kind person has answered. Google it.

## What's gone wrong?

Each chapter has a "what's gone wrong?" section near the end, discussing some typical potholes that we all fall into from time to time. Look there especially if you don't see the results from the code in the book that you were expecting.

We actually start the book with one classic pitfall: R is *case sensitive*, which can be quite a culture shock if you're brought up on other systems. This matters for filenames as well as code. When in doubt, check the case!

